Traceback (most recent call last):
  File "/Users/marcusjackson/Desktop/foo34.py", line 9, in <module>
    print is_a_volunteer('jinnyhyunjikim')
  File "/Users/marcusjackson/Desktop/foo34.py", line 4, in is_a_volunteer
    for volunteer in csv.reader(open("static/volunteers/screen-names.csv")):
IOError: [Errno 2] No such file or directory: 'static/volunteers/screen-names.csv'
>>> 